### ISSUE TITLE
桌面右键新建文件后，桌面计算机、回收站、个人文件夹消失，刷新后与创建的文件重叠

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#39] opened 2020-02-24 09:34 UTC
After right-clicking on the desktop to create a new file, the desktop computer, recycle bin, and personal folders disappear. After refreshing, it overlaps with the created file.

**Comment by Yue-Lan** [comment] 2020-02-25 02:23
Duplicate of #41

**Closed** 2020-03-09 09:27 UTC
Labels: duplicate
